# Config file for a project
# Placed in $SRCROOT/zcbe/conf.toml
[package]
name = "ImageMagick"
ver = "7.1.1-47"

[deps]
req = [
"fftw",
"fontconfig",
"freetype",
"jpeg",
"lcms2",
"libheif",
"libpng",
"libxml2",
"libwebp",
"mingw-w64",
"openjpeg",
"tiff",
"xz",
"zlib",
"zstd",
]
