# Build config file
# Placed in currnt working directory of zcbe
[info]
build-name = "zmymingw-64"
prefix = "/home/zmy/zmymingw/64"
hostname = "x86_64-w64-mingw32"

[deps]
build = [
"autopoint",
"cmake",
"autoconf",
"automake",
"libtool",
"gettext",
"texinfo",
"pkg-config"
]

[env]
PKG_CONFIG_PATH = "${ZCPREF}/lib/pkgconfig"
PKG_CONFIG_LIBDIR = "${ZCPREF}/lib/pkgconfig"
