# Map for proj name and proj working dir

[mapping]
bzip2 = "archival/bzip2"
gzip = "archival/gzip"
lzip = "archival/lzip-1.25"
unrar = "archival/unrar"
unzip = "archival/unzip60"
xz = "archival/xz"
zip = "archival/zip30"
zstd = "archival/zstd"
autoconf = "devel/autoconf"
automake = "devel/automake"
binutils = "devel/binutils"
bison = "devel/bison"
cmake = "devel/cmake"
ctags = "devel/ctags-5.8-ported"
flex = "devel/flex-2.5.4a"
gcc = "devel/gcc"
gdb = "devel/gdb"
gdbm = "devel/gdbm"
help2man = "devel/help2man-1.47.14"
libtool = "devel/libtool"
lua = "devel/lua"
m4 = "devel/m4"
make = "devel/make"
nasm = "devel/nasm"
ninja = "devel/ninja"
pkgconf = "devel/pkgconf"
tcl = "devel/tcl"
tk = "devel/tk"
yasm = "devel/yasm"
cairo = "libraries/cairo"
libarchive = "libraries/libarchive"
expat = "libraries/libexpat"
fftw = "libraries/fftw-3.3.8"
flac = "libraries/flac"
freetype = "libraries/freetype"
frei0r = "libraries/frei0r"
fribidi = "libraries/fribidi"
fontconfig = "libraries/fontconfig"
gc = "libraries/bdwgc"
graphite2 = "libraries/graphite"
giflib = "libraries/giflib"
glib = "libraries/glib"
gmp = "libraries/gmp-6.2.0"
gpgme = "libraries/gpgme"
isl = "libraries/isl"
jpeg = "libraries/jpeg-9f"
lame = "libraries/lame-3.100"
lcms2 = "libraries/lcms2"
libassuan = "libraries/libassuan"
libcares = "libraries/c-ares"
libffi = "libraries/libffi"
libgcrypt = "libraries/libgcrypt"
libgd = "libraries/libgd"
libgpg-error = "libraries/libgpg-error"
libheif = "libraries/libheif"
libiconv = "libraries/libiconv"
libid3tag = "libraries/libid3tag-0.15.1b"
libintl = "libraries/libintl"
libksba = "libraries/libksba"
libmad = "libraries/libmad"
libogg = "libraries/ogg"
libpng = "libraries/libpng"
libpsl = "libraries/libpsl"
libgit2 = "libraries/libgit2"
libressl = "libraries/libressl-4.0.0"
libsndfile = "libraries/libsndfile"
libssh2 = "libraries/libssh2"
libtasn1 = "libraries/libtasn1"
libwebp = "libraries/libwebp"
libxml2 = "libraries/libxml2"
libgnurx = "libraries/mingw-libgnurx-2.5.1"
mingw-w64 = "libraries/mingw-w64"
mpc = "libraries/mpc"
mpfr = "libraries/mpfr"
nettle = "libraries/nettle"
npth = "libraries/npth"
ntbtls = "libraries/ntbtls"
openjpeg = "libraries/openjpeg"
opus = "libraries/opus"
opusfile = "libraries/opusfile"
p11-kit = "libraries/p11-kit"
pcre = "libraries/pcre2"
pdcurses = "libraries/pdcurses"
pixman = "libraries/pixman"
readline = "libraries/readline"
sdl2 = "libraries/SDL2-2.0.12"
slib = "libraries/slib"
termcap = "libraries/termcap-1.3.1"
tiff = "libraries/libtiff"
vorbis = "libraries/vorbis"
wxWidgets = "libraries/wxWidgets"
x264 = "libraries/x264"
x265 = "libraries/x265"
xvid = "libraries/xvidcore-1.3.7"
zlib = "libraries/zlib"
aria2 = "user/aria2"
bc = "user/bc-1.08.1"
curl = "user/curl"
diffutils = "user/diffutils"
ffmpeg = "user/ffmpeg"
file = "user/file"
gnupg = "user/gnupg"
grep = "user/grep"
ImageMagick = "user/ImageMagick"
less = "user/less"
pinentry = "user/pinentry"
sed = "user/sed"
sqlite = "user/sqlite-autoconf-3490100"
