# Map for proj name and proj working dir

[mapping]
bzip2 = "archival/bzip2-1.0.6"
gzip = "archival/gzip"
lzip = "archival/lzip-1.19"
tar = "archival/tar-1.13"
unrar = "archival/unrar"
unzip = "archival/unzip60"
xz = "archival/xz"
zip = "archival/zip30"
zstandard = "archival/zstd"
autoconf = "devel/autoconf"
automake = "devel/automake-1.16.1"
binutils = "devel/binutils-2.29.1"
bison = "devel/bison-2.4.1"
cmake = "devel/cmake"
ctags = "devel/ctags-5.8-ported"
flex = "devel/flex-2.5.4a"
gcc = "devel/gcc-9.3.0"
gdb = "devel/gdb-9.1"
gdbm = "devel/gdbm-1.13"
help2man = "devel/help2man-1.47.14"
libtool = "devel/libtool-2.4.6"
lua = "devel/lua-5.3.4-ported"
LuaJIT = "devel/LuaJIT-2.0.5-ported"
m4 = "devel/m4-1.4.18"
make = "devel/make"
nasm = "devel/nasm-2.14rc15"
pkg-config = "devel/pkg-config-0.29"
tcc = "devel/tcc-0.9.26"
tcl = "devel/tcl8.7a1"
tk = "devel/tk8.7a1"
yasm = "devel/yasm-1.3.0"
cairo = "libraries/cairo"
expat = "libraries/libexpat"
fftw = "libraries/fftw-3.3.8"
flac = "libraries/flac"
freetype = "libraries/freetype-2.9"
fribidi = "libraries/fribidi-1.0.4"
fontconfig = "libraries/fontconfig-2.13.0"
gc = "libraries/bdwgc"
graphite2 = "libraries/graphite2-1.3.12"
giflib = "libraries/giflib-5.1.4"
glib = "libraries/glib-2.50.0"
gmp = "libraries/gmp-6.2.0"
gpgme = "libraries/gpgme-1.13.1"
isl = "libraries/isl-0.19"
jpeg = "libraries/jpeg-9c"
lame = "libraries/lame-3.100"
lcms2 = "libraries/lcms2"
libassuan = "libraries/libassuan-2.5.3"
libcares = "libraries/c-ares"
libffi = "libraries/libffi"
libgcrypt = "libraries/libgcrypt-1.8.5"
libgd = "libraries/libgd-2.2.5"
libgpg-error = "libraries/libgpg-error-1.37"
libheif = "libraries/libheif"
libiconv = "libraries/libiconv-1.15"
libid3tag = "libraries/libid3tag-0.15.1b"
libintl = "libraries/libintl"
libksba = "libraries/libksba-1.3.5"
libmad = "libraries/libmad-0.15.1b"
libogg = "libraries/ogg"
libpng = "libraries/libpng"
libressl = "libraries/libressl-3.0.2"
libsndfile = "libraries/libsndfile"
libssh2 = "libraries/libssh2"
libtasn1 = "libraries/libtasn1-4.12"
libunistring = "libraries/libunistring-0.9.8"
libuv= "libraries/libuv"
libwebp = "libraries/libwebp"
libxml2 = "libraries/libxml2"
libgnurx = "libraries/mingw-libgnurx-2.5.1"
mingw-w64 = "libraries/mingw-w64-7.0.0"
mpc = "libraries/mpc-1.1.0"
mpfr = "libraries/mpfr-4.0.1"
msgpack = "libraries/msgpack"
nettle = "libraries/nettle-3.3"
npth = "libraries/npth-1.6"
ntbtls = "libraries/ntbtls-0.1.2"
openjpeg = "libraries/openjpeg"
opus = "libraries/opus"
opusfile = "libraries/opusfile"
p11-kit = "libraries/p11-kit-0.23.2"
pcre = "libraries/pcre-8.44"
pdcurses = "libraries/PDCurses-3.4-ported"
pixman = "libraries/pixman"
readline = "libraries/readline-8.0"
sdl2 = "libraries/SDL2-2.0.7-ported"
termcap = "libraries/termcap-1.3.1"
tiff = "libraries/libtiff"
vorbis = "libraries/vorbis"
wxWidgets = "libraries/wxWidgets"
x264 = "libraries/x264"
x265 = "libraries/x265"
xvid = "libraries/xvidcore-1.3.5"
zlib = "libraries/zlib"
aria2 = "user/aria2"
bc = "user/bc-1.07.1-ported"
curl = "user/curl"
diffutils = "user/diffutils-3.6-ported"
ffmpeg = "user/ffmpeg"
file = "user/file-5.32"
gnupg = "user/gnupg-2.2.20"
grep = "user/grep-3.4"
ImageMagick = "user/ImageMagick"
less = "user/less-530"
pinentry = "user/pinentry-1.1.0"
sed = "user/sed"
sqlite = "user/sqlite-autoconf-3250300"
vim = "user/vim81"
