# Map for proj name and proj working dir

[mapping]
bzip2 = "archival/bzip2"
gzip = "archival/gzip"
lzip = "archival/lzip-1.19"
unrar = "archival/unrar"
unzip = "archival/unzip60"
xz = "archival/xz"
zip = "archival/zip30"
zstandard = "archival/zstd"
autoconf = "devel/autoconf"
automake = "devel/automake-1.16.2"
binutils = "devel/binutils-2.29.1"
bison = "devel/bison"#-2.4.1"
cmake = "devel/cmake"
ctags = "devel/ctags-5.8-ported"
flex = "devel/flex-2.5.4a"
gcc = "devel/gcc"
gdb = "devel/gdb"
gdbm = "devel/gdbm-1.13"
help2man = "devel/help2man-1.47.14"
libtool = "devel/libtool"
lua = "devel/lua-5.3.4-ported"
luajit = "devel/luajit"
m4 = "devel/m4-1.4.18"
make = "devel/make"
nasm = "devel/nasm"
pkg-config = "devel/pkg-config"
tcc = "devel/tcc-0.9.26"
tcl = "devel/tcl8.7a1"
tk = "devel/tk8.7a1"
yasm = "devel/yasm"
cairo = "libraries/cairo"
libarchive = "libraries/libarchive"
expat = "libraries/libexpat"
fftw = "libraries/fftw-3.3.8"
flac = "libraries/flac"
freetype = "libraries/freetype-2.9"
fribidi = "libraries/fribidi-1.0.4"
fontconfig = "libraries/fontconfig-2.13.0"
gc = "libraries/bdwgc"
graphite2 = "libraries/graphite2-1.3.12"
giflib = "libraries/giflib-5.1.4"
glib = "libraries/glib"
gmp = "libraries/gmp-6.2.0"
gpgme = "libraries/gpgme"
isl = "libraries/isl-0.19"
jpeg = "libraries/jpeg-9c"
lame = "libraries/lame-3.100"
lcms2 = "libraries/lcms2"
libassuan = "libraries/libassuan"
libcares = "libraries/c-ares"
libffi = "libraries/libffi"
libgcrypt = "libraries/libgcrypt"
libgd = "libraries/libgd-2.2.5"
libgpg-error = "libraries/libgpg-error"
libheif = "libraries/libheif"
libiconv = "libraries/libiconv-1.15"
libid3tag = "libraries/libid3tag-0.15.1b"
libintl = "libraries/libintl"
libksba = "libraries/libksba"
libmad = "libraries/libmad-0.15.1b"
libogg = "libraries/ogg"
libpng = "libraries/libpng"
libgit2 = "libraries/libgit2"
libressl = "libraries/libressl-3.2.2"
libsndfile = "libraries/libsndfile"
libssh2 = "libraries/libssh2"
libtasn1 = "libraries/libtasn1-4.12"
libunistring = "libraries/libunistring"
unibilium = "libraries/unibilium"
libuv= "libraries/libuv"
libluv= "libraries/luv"
libvterm = "libraries/libvterm"
libtermkey = "libraries/libtermkey"
libwebp = "libraries/libwebp"
libxml2 = "libraries/libxml2"
libgnurx = "libraries/mingw-libgnurx-2.5.1"
mingw-w64 = "libraries/mingw-w64"
mpc = "libraries/mpc-1.2.1"
mpfr = "libraries/mpfr-4.1.0"
msgpack = "libraries/msgpack"
nettle = "libraries/nettle-3.3"
npth = "libraries/npth"
ntbtls = "libraries/ntbtls"
openjpeg = "libraries/openjpeg"
opus = "libraries/opus"
opusfile = "libraries/opusfile"
p11-kit = "libraries/p11-kit-0.23.2"
pcre = "libraries/pcre-8.44"
pdcurses = "libraries/pdcurses"
pixman = "libraries/pixman"
readline = "libraries/readline"
sdl2 = "libraries/SDL2-2.0.12"
slib = "libraries/slib"
termcap = "libraries/termcap-1.3.1"
tiff = "libraries/libtiff"
tree-sitter = "libraries/tree-sitter"
vorbis = "libraries/vorbis"
winpty = "libraries/winpty"
wxWidgets = "libraries/wxWidgets"
x264 = "libraries/x264"
x265 = "libraries/x265"
xvid = "libraries/xvidcore-1.3.7"
zlib = "libraries/zlib"
aria2 = "user/aria2"
bc = "user/bc-1.07.1-ported"
curl = "user/curl"
diffutils = "user/diffutils"
ffmpeg = "user/ffmpeg"
file = "user/file-5.32"
gnupg = "user/gnupg"
grep = "user/grep-3.4"
ImageMagick = "user/ImageMagick"
less = "user/less-530"
pinentry = "user/pinentry"
sed = "user/sed"
sqlite = "user/sqlite-autoconf-3250300"
neovim = "user/neovim"
