# Config file for a project
# Placed in $SRCROOT/zcbe/conf.toml
[package]
name = "cairo"
ver = "git"

[deps]
rep = [
"fontconfig",
"freetype",
"libintl",
"glib",
"libffi",
"libpng",
"pcre",
"pixman",
]
