# Config file for a project
# Placed in $SRCROOT/zcbe/conf.toml
[package]
name = "ffmpeg"
ver = "4.4"

[deps] # Dependencies
req = [
"fontconfig",
"freetype",
"frei0r",
"lame",
"libressl",
"libxml2",
"libwebp",
"opus",
"sdl2",
"vorbis",
"x264",
"x265",
"xvid",
"xz",
]
