# Config file for a project
# Placed in $SRCROOT/zcbe/conf.toml
[package]
name = "pinentry"
ver = "1.3.1"

[deps] # Dependencies
req = [
"libiconv",
"libgpg-error",
"libassuan",
]

[env]
CC = "${ZCHOST}-gcc"
