# Config file for a project
# Placed in $SRCROOT/zcbe/conf.toml
[package]
name = "gdb"
ver = "16.2"

[deps]
build = [
"bison",
"flex"
]
req=[
"pdcurses",
"readline",
"termcap",
"expat",
"mpfr"
]

[env]
CC = "${ZCHOST}-gcc"
