# Config file for a project
# Placed in $SRCROOT/zcbe/conf.toml
[package]
name = "curl"
ver = "8.13.0"

[deps]
req = [
"libpsl",
"libssh2",
"libressl",
"zlib",
]

[env]
CC = "${ZCHOST}-gcc"
LDFLAGS = "-L${ZCPREF}/lib"
CFLAGS = "-I${ZCPREF}/include"
