# Config file for a project
# Placed in $SRCROOT/zcbe/conf.toml
[package]
name = "curl"
ver = "git"

[deps]
req = [
"libssh2",
"libressl",
"zlib",
]

[env]
LDFLAGS = "-L${ZCPREF}/lib"
CFLAGS = "-I${ZCPREF}/include"
