# Config file for a project
# Placed in $SRCROOT/zcbe/conf.toml
[package]
name = "libarchive"
ver = "3.7.9"

[deps]
req = [
"zstd",
"libxml2",
"zlib",
"xz",
"bzip2",
"pcre",
"libressl",
"nettle",
]

[env]
CC = "${ZCHOST}-gcc"
