# This is a basic workflow to help you get started with Actions

name: Build zmymingw

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        host_trip: ["x86_64-w64-mingw32", "i686-w64-mingw32"]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 2048
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          sudo apt update
          sudo apt install -y build-essential
          sudo apt clean
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bash_profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> "$GITHUB_PATH"

      # Install dependencies, python, ZCBE, mingw and others
      - name: Install dependencies
        env:
          HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
          HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
          HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
        run: |
          brew install -q \
          autoconf automake libtool gettext texinfo pkg-config texi2html groff asciidoc \
          xmlto python3 perl imagemagick meson ninja bison flex gperf docbook-xsl \
          help2man ed autoconf-archive fig2dev ccache castxml docbook2x file nasm \
          gtk-doc sphinx-doc file curl po4a mingw-w64 docbook
          brew cleanup --prune=all || true
          python3 -m pip install zcbe==v0.5.0

      - name: Check out submodules
        run: |
          git submodule init
          git submodule update
          
      # Set build.toml
      - name: Set build parameters
        env:
          HOST_TRIP: ${{ matrix.host_trip }}
        run: sh set_up_ghaction.sh

      - name: Ccache
        uses: actions/cache@v4
        with:
          path: /home/runner/.ccache
          key: ccache:${{ matrix.host_trip}}:${{ github.ref }}:${{ github.sha }}
          restore-keys: |
            ccache:${{ matrix.host_trip}}:${{ github.ref }}
            ccache:${{ matrix.host_trip}}

      # Whatever it built is considered as success
      - name: Build GCC, binutils, GDB, and LLVM
        run: |
          sh -c 'python3 -m zcbe -syj8 gcc || true'
          sh -c 'python3 -m zcbe -sy llvm || true'

      - name: Build the rest
        run: |
          sh -c 'python3 -m zcbe -sayj8 || true'
          sh -c 'python3 -m zcbe -sayj8 || true'

      - name: Strip binaries
        run: |
          find /home/runner/artifact -name "*.exe" -o -name "*.dll" -exec ${ matrix.host_trip }-strip --strip-all {} \;

      - name: Package the result
        run: |
          cd /home/runner/artifact
          tar -Jcf ${{ matrix.host_trip }}.tar.xz ${{ matrix.host_trip }}

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.host_trip }}.tar.xz
          path: /home/runner/artifact/${{ matrix.host_trip }}.tar.xz
